name: curation_workflow
channels:
  - conda-forge 
dependencies:
  - chembl_structure_pipeline
  - chembl_webresource_client
  - ipywidgets==7.7.0
  - openpyxl
  - pandas
  - rdkit==2021.03.5
  - pip:
    - "https://github.com/phi-grib/Data_curation/archive/master.zip"
    - "https://github.com/phi-grib/standardiser/archive/master.zip"
    - "https://github.com/phi-grib/EPA_simplified/archive/master.zip"
