name: curation_workflow
channels:
  - default
  - rdkit
  - conda-forge 
  - chembl
dependencies:
  - ipywidgets==7.7.0
  . openpyxl
  - pandas
  - rdkit==2021.03.5
  - pip:
    - chembl_webresource_client
    - "https://github.com/phi-grib/Data_curation/archive/master.zip"
